//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""CharacterMove"",
            ""id"": ""72bde5eb-a9c6-4ebd-a8ee-9e418d95ad8a"",
            ""actions"": [
                {
                    ""name"": ""Touch"",
                    ""type"": ""Button"",
                    ""id"": ""ea19a6d7-cdc7-43a9-80e3-6e40dff3e963"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Swipe"",
                    ""type"": ""Value"",
                    ""id"": ""24a61ac7-df3d-43da-881b-9e9b08ba76a8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ff2d3f0c-5939-4fb1-8042-6abfae13f3b8"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c58ac3f7-8742-445c-a145-0cd0ee5d4d85"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8e057e6-1846-49be-be82-5664e982e2ce"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d334a910-a9d5-439c-b4ac-206e66db61df"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a8a5692b-916b-4cff-8399-638b30d294ad"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swipe"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6f70ac2a-d42f-4bdb-ba71-5c3bab90bdd2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3ec6710f-da2d-429b-9ed2-62d0849cacfd"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""22fa9b3d-2463-4c2e-845a-6476a072ddce"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a03f41fa-8a5b-4fbf-bf05-458862e24fed"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""CharacterFight"",
            ""id"": ""7a20b062-7a9c-4e95-bf2f-5468d205c538"",
            ""actions"": [
                {
                    ""name"": ""Fight"",
                    ""type"": ""Button"",
                    ""id"": ""eab5de88-79fb-44b6-ad2d-4524c8cf0ac2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""91ee54fd-c4bb-45a6-b02d-be5bbfc47ecb"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c42a646-0d1e-47b6-819a-e8445250ed8d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CharacterMove
        m_CharacterMove = asset.FindActionMap("CharacterMove", throwIfNotFound: true);
        m_CharacterMove_Touch = m_CharacterMove.FindAction("Touch", throwIfNotFound: true);
        m_CharacterMove_Swipe = m_CharacterMove.FindAction("Swipe", throwIfNotFound: true);
        // CharacterFight
        m_CharacterFight = asset.FindActionMap("CharacterFight", throwIfNotFound: true);
        m_CharacterFight_Fight = m_CharacterFight.FindAction("Fight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterMove
    private readonly InputActionMap m_CharacterMove;
    private List<ICharacterMoveActions> m_CharacterMoveActionsCallbackInterfaces = new List<ICharacterMoveActions>();
    private readonly InputAction m_CharacterMove_Touch;
    private readonly InputAction m_CharacterMove_Swipe;
    public struct CharacterMoveActions
    {
        private @InputControls m_Wrapper;
        public CharacterMoveActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Touch => m_Wrapper.m_CharacterMove_Touch;
        public InputAction @Swipe => m_Wrapper.m_CharacterMove_Swipe;
        public InputActionMap Get() { return m_Wrapper.m_CharacterMove; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterMoveActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterMoveActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterMoveActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterMoveActionsCallbackInterfaces.Add(instance);
            @Touch.started += instance.OnTouch;
            @Touch.performed += instance.OnTouch;
            @Touch.canceled += instance.OnTouch;
            @Swipe.started += instance.OnSwipe;
            @Swipe.performed += instance.OnSwipe;
            @Swipe.canceled += instance.OnSwipe;
        }

        private void UnregisterCallbacks(ICharacterMoveActions instance)
        {
            @Touch.started -= instance.OnTouch;
            @Touch.performed -= instance.OnTouch;
            @Touch.canceled -= instance.OnTouch;
            @Swipe.started -= instance.OnSwipe;
            @Swipe.performed -= instance.OnSwipe;
            @Swipe.canceled -= instance.OnSwipe;
        }

        public void RemoveCallbacks(ICharacterMoveActions instance)
        {
            if (m_Wrapper.m_CharacterMoveActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterMoveActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterMoveActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterMoveActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterMoveActions @CharacterMove => new CharacterMoveActions(this);

    // CharacterFight
    private readonly InputActionMap m_CharacterFight;
    private List<ICharacterFightActions> m_CharacterFightActionsCallbackInterfaces = new List<ICharacterFightActions>();
    private readonly InputAction m_CharacterFight_Fight;
    public struct CharacterFightActions
    {
        private @InputControls m_Wrapper;
        public CharacterFightActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Fight => m_Wrapper.m_CharacterFight_Fight;
        public InputActionMap Get() { return m_Wrapper.m_CharacterFight; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterFightActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterFightActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterFightActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterFightActionsCallbackInterfaces.Add(instance);
            @Fight.started += instance.OnFight;
            @Fight.performed += instance.OnFight;
            @Fight.canceled += instance.OnFight;
        }

        private void UnregisterCallbacks(ICharacterFightActions instance)
        {
            @Fight.started -= instance.OnFight;
            @Fight.performed -= instance.OnFight;
            @Fight.canceled -= instance.OnFight;
        }

        public void RemoveCallbacks(ICharacterFightActions instance)
        {
            if (m_Wrapper.m_CharacterFightActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterFightActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterFightActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterFightActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterFightActions @CharacterFight => new CharacterFightActions(this);
    public interface ICharacterMoveActions
    {
        void OnTouch(InputAction.CallbackContext context);
        void OnSwipe(InputAction.CallbackContext context);
    }
    public interface ICharacterFightActions
    {
        void OnFight(InputAction.CallbackContext context);
    }
}
